name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: echo Add other actions to build
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          
      - name: go into test folder
        run: cd /TAU/3/
        
      - name: RunAmazonCartTest
        run: python test_checkout.py 
      
      - name: list
        run: ls

